### ISSUE TITLE
parameters.xlsx file not found 

### ISSUE THREAD

**Issue by farukmoonschi** [Campbell-Muscle-Lab/SLControl_analysis#1]
This issue arises because of the incorrect path of the excel files assigned on lines 1281 and 1292. So I changed the codes, "code\parameters" to "parameters". Also, this code throw an exception when this code containing folder is not the cd. So I replaced cd with fileparts(which(mfilename)) in lines 1280 and 1291.

**Comment by farukmoonschi** [comment]
I solved the issue and verification by Ken would be nice.

**Comment by kenatcampbellmusclelab** [comment]
@farukmoonschi - thanks, this probably happened when I rearranged the folders to try and improve the structure. The second bit means you don't have to set the working directly at the start so is an improvement.

Did you push the commit?

**Comment by farukmoonschi** [comment]
I can see the same cd and path issue in multiple other places in the code. I will correct those issues and push the commit.

**Comment by kenatcampbellmusclelab** [comment]
Great. Close this issue when you are done.
